export const OUR_PATH_TO_LAMBDATEST_SKILL: Record<string, string> = {
  "appium-automation-skill": "appium-skill",
  "behat-automation-skill": "behat-skill",
  "behave-automation-skill": "behave-skill",
  "capybara-automation-skill": "capybara-skill",
  "cicd-pipeline-skill": "cicd-pipeline-skill",
  "codeception-testing-skill": "codeception-skill",
  "cucumber-automation-skill": "cucumber-skill",
  "cypress-automation-skill": "cypress-skill",
  "detox-automation-skill": "detox-skill",
  "espresso-automation-skill": "espresso-skill",
  "flutter-testing-skill": "flutter-testing-skill",
  "gauge-automation-skill": "gauge-skill",
  "geb-automation-skill": "geb-skill",
  "hyperexecute-skill": "hyperexecute-skill",
  "jasmine-testing-skill": "jasmine-skill",
  "jest-testing-skill": "jest-skill",
  "junit-testing-skill": "junit-5-skill",
  "karma-testing-skill": "karma-skill",
  "laravel-dusk-skill": "laravel-dusk-skill",
  "lettuce-testing-skill": "lettuce-skill",
  "mocha-testing-skill": "mocha-skill",
  "mstest-testing-skill": "mstest-skill",
  "nemojs-automation-skill": "nemojs-skill",
  "nightwatchjs-automation-skill": "nightwatchjs-skill",
  "nunit-testing-skill": "nunit-skill",
  "phpunit-testing-skill": "phpunit-skill",
  "playwright-automation-skill": "playwright-skill",
  "protractor-automation-skill": "protractor-skill",
  "puppeteer-automation-skill": "puppeteer-skill",
  "pytest-testing-skill": "pytest-skill",
  "robot-framework-skill": "robot-framework-skill",
  "rspec-testing-skill": "rspec-skill",
  "selenide-automation-skill": "selenide-skill",
  "selenium-automation-skill": "selenium-skill",
  "serenity-bdd-skill": "serenity-bdd-skill",
  "smartui-testing-skill": "smartui-skill",
  "specflow-automation-skill": "specflow-skill",
  "testcafe-automation-skill": "testcafe-skill",
  "testng-testing-skill": "testng-skill",
  "testunit-ruby-skill": "testunit-skill",
  "unittest-testing-skill": "unittest-skill",
  "vitest-testing-skill": "vitest-skill",
  "webdriverio-automation-skill": "webdriverio-skill",
  "xcuitest-automation-skill": "xcuitest-skill",
  "xunit-testing-skill": "xunit-skill",
  "test-framework-migration-skill": "test-framework-migration-skill",
};

export function getLambdaTestSkillName(ourPath: string): string {
  return OUR_PATH_TO_LAMBDATEST_SKILL[ourPath] ?? ourPath;
}
